from os.path import join
import pandas as pd
from collections import defaultdict
import yaml
import csv

###############################################################
# set snakemake config params
###############################################################
# dir paths
out_dir = config['out_dir']
data_dir = config['data_dir']

# manifests
sample_manifest = config['sampleManifest']

###############################################################
# create sample lists
###############################################################
#dict sample_id: filename
def CreateSampleDicts(df_s):
    s_dict={}
    s_dict = dict(zip(df_s.sample_id, df_s.filename))

    return(s_dict)

#create lists of sample ids, filenames
def CreateProjLists(dict_s):
    sp_list = []
    file_list = []

    #multiplex,sample
    for k,v in dict_s.items():
        file_list.append(v)
        sp_list.append(k)
    return(sp_list,file_list)

###############################################################
# snakemake functions
###############################################################
#get list of fq names based on multiplex name
def get_input_files(wildcards):
    #example: {data_dir}/{sample_id.fastq.gz}
    fq = join(data_dir,samp_dict[wildcards.sp])
    return(fq)

def get_rulec_cmd(wildcards):
    cmd='cat '
    sp_paths=''
    for sp in sp_list:
        # set source (ruleB) and destination files
        source = join(out_dir, sp + '_rulea.txt')

        # create command
        sp_paths = source + ' ' + sp_paths
    
    # add output path    
    destination = join(out_dir, 'final_output','merged_rulea.txt')
    cmd = cmd + sp_paths + ' >> ' + destination

    return(cmd)

def get_ruled_cmd(wildcards):
    cmd=''
    for sp in sp_list:
        # set source (ruleB) and destination files
        source = join(out_dir, wildcards.sp + '_ruleb.txt')
        destination = join(out_dir, 'final_output', wildcards.sp + '_copied_ruleb.txt')

        # cp the the files
        cmd = 'cp ' + source + ' ' + destination + '; ' + cmd
        print(cmd)

    return(cmd)
###############################################################
# main code
###############################################################
#read manifests
df_samples = pd.read_csv(sample_manifest,sep=",")

#create dicts
(samp_dict) = CreateSampleDicts(df_samples)

#create unique sample_id and filename_list
#sp_list    filename
#sample1        sample1.fq
#sample1        sample2.fq
(sp_list,file_list) = CreateProjLists(samp_dict)

rule all:
    input:
        # input files
        expand(join(data_dir,'{fq}'),fq=file_list),

        # ruleA output
        expand(join(out_dir,'{sp}_rulea.txt'),sp=sp_list),
 
        # ruleB output
        expand(join(out_dir,'{sp}_ruleb.txt'),sp=sp_list),

        # ruleC output
        join(out_dir,'final_output','merged_rulea.txt'),

        # ruleD output
        expand(join(out_dir,'final_output','{sp}_copied_ruleb.txt'),sp=sp_list)

rule A:
    input:
        fq = join(data_dir,'{sp}.fq')
    output:
        final = temp(join(out_dir,'{sp}_rulea.txt'))
    shell:
        '''
        cat {input.fq} > {output.final}
        echo "\nruleA completed" >> {output.final}
        '''

rule B:
    input:
        fq = get_input_files
    output:
        final = temp(join(out_dir,'{sp}_ruleb.txt'))
    shell:
        '''
        cat {input.fq} > {output.final}
        echo "\nruleB completed" >> {output.final}
        '''

rule C:
    input:
        rulea = expand(join(out_dir,'{sp}_rulea.txt'),sp=sp_list)
    params:
        cmd = get_rulec_cmd
    output:
        final = join(out_dir,'final_output','merged_rulea.txt')
    shell:
        '''
        # create the final output file
        touch {output.final}

        # run the cat command
        {params.cmd}
        '''

rule D:
    input:
        ruleb = rules.B.output.final
    params:
        cmd = get_ruled_cmd
    output:
        final = join(out_dir, 'final_output', '{sp}_copied_ruleb.txt')
    shell:
        '''
        # run the command
        {params.cmd}
        '''